### ISSUE TITLE
Support for touch devices

### ISSUE THREAD

**Issue by TylerRick** [Lane/angular-drag-and-drop#1]
I really like what you have so far. I hope you continue to develop it.

One feature that I think a lot of people would appreciate is support for touch/mobile devices.

https://github.com/fatlinesofcode/ngDraggable has this, for example.

**Comment by TylerRick** [comment]
I don't know if it would be as easy as adding a polyfill/shim, but if possible, that would be a really easy solution.

See, for example:
- https://github.com/timruffles/ios-html5-drag-drop-shim or
- https://github.com/furf/jquery-ui-touch-punch

**Comment by Lane** [comment]
Hey, sorry for the delay getting to this issue.  The latest commits have been tested on Android 6 and iOS9 devices and should work fine.
